
import React from 'react';
import { Footer } from '../components/layout/Footer';

export const Privacy: React.FC<{ onNavigate: (view: string) => void }> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-[#0f172a] text-slate-300 font-sans">
      <nav className="border-b border-slate-800 bg-[#0f172a]/80 backdrop-blur sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 py-4 flex justify-between items-center">
             <button onClick={() => onNavigate('landing')} className="font-bold text-white text-lg">Mango</button>
             <button onClick={() => onNavigate('dashboard')} className="text-xs bg-slate-800 hover:bg-slate-700 px-3 py-1.5 rounded text-white transition-colors">Go to App</button>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-black text-white mb-4 font-display">Privacy Policy</h1>
        <p className="text-slate-500 mb-12 text-sm">Last updated: January 14, 2026</p>

        <div className="space-y-12 text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-4">1. Introduction</h2>
            <p>
              Hi there. At Mango, we believe privacy policies should be readable by humans, not just lawyers. 
              We value your trust and we're committed to protecting your data. This policy explains what we collect, 
              why we collect it, and how we handle it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">2. Information We Collect</h2>
            <p className="mb-4">We collect the minimum amount of data necessary to run our service:</p>
            <ul className="list-disc pl-5 space-y-2 text-slate-400">
              <li><strong>Account Info:</strong> Your name, email, and billing details (handled securely by Stripe).</li>
              <li><strong>Usage Data:</strong> Inputs you provide to our AI agents (e.g., product descriptions, URLs) and the images you generate.</li>
              <li><strong>Technical Data:</strong> IP address, browser type, and device info to help us debug issues and prevent fraud.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">3. How We Use Your Information</h2>
            <p>
              We use your data to:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2 text-slate-400">
              <li>Generate your ad creatives (obviously).</li>
              <li>Improve our AI models (e.g., understanding which prompts yield the best CTR).</li>
              <li>Send you billing receipts and critical product updates.</li>
            </ul>
            <p className="mt-4 font-bold text-white">We do NOT sell your personal data to third parties.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">4. AI Generated Content</h2>
            <p>
              The images and copy generated by Mango are processed using our advanced AI models. 
              While we store these assets so you can access your library, we do not claim ownership over them. 
              Your inputs are processed securely and are not used to train public models in a way that would expose your proprietary data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">5. Cookies</h2>
            <p>
              We use cookies to keep you logged in and to analyze how people use our website. You can block cookies in your browser settings, but some parts of the app might not work perfectly.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">6. Security</h2>
            <p>
              We use industry-standard encryption (TLS) for all data in transit. Your billing information is never stored on our servers; it lives securely with our payment processor, Stripe.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">7. Contact Us</h2>
            <p>
              Have questions about your data? Reach out to us directly at <a href="mailto:privacy@usemango.ai" className="text-brand-400 hover:underline">privacy@usemango.ai</a>.
            </p>
          </section>
        </div>
      </main>
      
      <Footer onNavigate={onNavigate} />
    </div>
  );
};
