
import React from 'react';
import { Footer } from '../components/layout/Footer';

export const Terms: React.FC<{ onNavigate: (view: string) => void }> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-[#0f172a] text-slate-300 font-sans">
      <nav className="border-b border-slate-800 bg-[#0f172a]/80 backdrop-blur sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 py-4 flex justify-between items-center">
             <button onClick={() => onNavigate('landing')} className="font-bold text-white text-lg">Mango</button>
             <button onClick={() => onNavigate('dashboard')} className="text-xs bg-slate-800 hover:bg-slate-700 px-3 py-1.5 rounded text-white transition-colors">Go to App</button>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-black text-white mb-4 font-display">Terms of Service</h1>
        <p className="text-slate-500 mb-12 text-sm">Effective Date: January 1, 2026</p>

        <div className="space-y-12 text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Mango, you agree to be bound by these Terms. If you don't agree, please don't use our service. It's that simple.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">2. The Service</h2>
            <p>
              Mango is an AI-powered platform that generates marketing assets. We provide the tools, but you are responsible for how you use the output.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">3. Ownership of Content (Important!)</h2>
            <div className="bg-brand-900/10 border border-brand-500/20 p-4 rounded-lg">
                <p className="text-brand-200 font-medium">
                  <strong>You own the output.</strong>
                </p>
                <p className="mt-2 text-slate-400">
                  Mango assigns to you all right, title, and interest in and to the images and copy generated by the Service for your account. You can use them for commercial ads, billboards, websites, or whatever you want.
                </p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">4. Payment & Credits</h2>
            <p>
              We offer subscription plans. Payments are non-refundable except as required by law. If you cancel, you keep access until the end of your billing cycle. Unused credits do not roll over to the next month unless specified in your plan.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">5. Prohibited Use</h2>
            <p>You agree not to use Mango to generate:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2 text-slate-400">
              <li>Illegal content or hate speech.</li>
              <li>Deepfakes of real people without consent.</li>
              <li>Content that infringes on third-party trademarks.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">6. Limitation of Liability</h2>
            <p>
              Mango is provided "as is". We are not liable for any lost profits or damages arising from your use of the generated assets. (e.g., if an ad doesn't convert, that's on the market, not us).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">7. Termination</h2>
            <p>
              We reserve the right to suspend accounts that abuse our system or violate these terms.
            </p>
          </section>
        </div>
      </main>
      
      <Footer onNavigate={onNavigate} />
    </div>
  );
};
