
import React from 'react';

export const FAQ: React.FC = () => {
  return (
    <section className="py-20 px-6 max-w-2xl mx-auto">
        <h2 className="text-2xl font-black font-display text-white text-center mb-8">Yeah, but...</h2>
        <div className="space-y-4">
            <div className="bg-slate-900/50 rounded-2xl p-6 border border-slate-800">
                <h3 className="font-bold text-sm mb-2 text-white">Does this replace designers?</h3>
                <p className="text-slate-400 text-xs leading-relaxed">For ad creatives? Yes. For complex branding or UI design? No. We focus 100% on performance marketing assets.</p>
            </div>
            <div className="bg-slate-900/50 rounded-2xl p-6 border border-slate-800">
                <h3 className="font-bold text-sm mb-2 text-white">Are the images copyright free?</h3>
                <p className="text-slate-400 text-xs leading-relaxed">100%. You own every pixel generated by Mango. Use them in ads, on your website, or print them on a billboard.</p>
            </div>
            <div className="bg-slate-900/50 rounded-2xl p-6 border border-slate-800">
                <h3 className="font-bold text-sm mb-2 text-white">What platforms are supported?</h3>
                <p className="text-slate-400 text-xs leading-relaxed">We optimize for Meta (Facebook/Instagram), TikTok, LinkedIn, and Pinterest.</p>
            </div>
        </div>
    </section>
  );
};
